DjangoViews/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.views.generic import RedirectView

from DjangoViews.views import SlugView
from contact.views import ContactView
from order.views import OrderView, ShipmentDetail, OrderHistoryView, OrderDetailView
from products.views import BrandCreate, BrandDetail, BrandList, BrandUpdate, BrandDelete, ProductCreate, ProductDetail, \
    ProductUpdate, ProductDelete, ProductList, CategoryDetail
from location.views import CountryDetail, CountryList, CountryUpdate, CountryDelete, CountryCreate
from django.conf.urls import url,include
from productuser import urls as user_urls
from django.conf import settings
from django.conf.urls.static import static
from cart.views import AddToCartView,CartDetail,CartEmptyView, RemoveCartItemView
from core.views import page_not_found
from products.ajax import add_comment,get_comments
from django.conf.urls import (
    handler400, handler403, handler404, handler500
)

from stores.views import StoreDetail, StoreList
from cart.ajax import get_cart_item_count, remove_cart_item

handler404 = page_not_found

urlpatterns = [
    url(r'^$',RedirectView.as_view(
        pattern_name='product_list',
        permanent=False)),
    url(r'^stores/$',StoreList.as_view(),name='store_list'),
    url(r'^admin/', admin.site.urls),
    url(r'^user/',include(user_urls,
                          app_name='productuser',
                          namespace='dj-auth')),
    url(r'^category/(?P<slug>[\w\-]+)/$',CategoryDetail.as_view(),name='category_detail'),
    # url(r'^brands/$',BrandList.as_view(),name='brand_list'),
    #url(r'^brand/create/$',BrandCreate.as_view(),name='brand_create'),
    url(r'^brand/(?P<slug>[\w\-]+)/$',BrandDetail.as_view(),name='brand_detail'),
    #url(r'^brand/(?P<slug>[\w\-]+)/update/$',BrandUpdate.as_view(),name='brand_update'),
    #url(r'^brand/(?P<slug>[\w\-]+)/delete/$',BrandDelete.as_view(),name='brand_delete'),
    url(r'^products/$',ProductList.as_view(),name='product_list'),
    # url(r'^product/create/$',ProductCreate.as_view(),name='product_create'),
    url(r'^product/(?P<product_id>[^/]+)/$',ProductDetail.as_view(),name='product_detail'),
    # url(r'^product/(?P<product_id>[^/]+)/update/$',ProductUpdate.as_view(),name='product_update'),
    # url(r'^product/(?P<product_id>[^/]+)/delete/$', ProductDelete.as_view(), name='product_delete'),
    url(r'^countries/$',CountryList.as_view(),name='country_list'),
    # url(r'^country/create/$',CountryCreate.as_view(),name='country_create'),
    # url(r'^country/(?P<slug>[\w\-]+)/$',CountryDetail.as_view(),name='country_detail'),
    # url(r'^country/(?P<slug>[\w\-]+)/update/$',CountryUpdate.as_view(),name='country_update'),
    # url(r'^country/(?P<slug>[\w\-]+)/delete/$',CountryDelete.as_view(),name='country_delete'),
    url(r'^contact/$',ContactView.as_view(),name='contact_create'),
    url(r'^addtocart/(?P<product_id>[^/]+)/$',AddToCartView.as_view(),name='add_to_cart'),
    url(r'^cart/$',CartDetail.as_view(),name='cart_detail'),
    url(r'^cart/empty/$',CartEmptyView.as_view(),name='cart_empty'),
    url(r'^order/$',OrderView.as_view(),name='order_form'),
    url(r'^shipment/(?P<shipment_id>[^/]+)/$',ShipmentDetail.as_view(),name='shipment_detail'),
    url(r'^order/history/$',OrderHistoryView.as_view(),name='order_history'),
    url(r'^order/(?P<order_id>[^/]+)/$',OrderDetailView.as_view(),name='order_detail'),
    url(r'^(?P<slug>[\w\-]+)/$',SlugView.as_view(),name='slug_view'),
    url(r'^ajax/add_comment/$',add_comment),
    url(r'^ajax/get_comments/$',get_comments),
    url(r'^ajax/get_cart_item_count/$',get_cart_item_count),
    url(r'^ajax/remove_cart_item/$',remove_cart_item),
    url(r'^store/(?P<slug>[\w\-]+)/$',StoreDetail.as_view(),name='store_detail'),
    url(r'^cart/remove_cart_item/$',RemoveCartItemView.as_view(),name='remove_cart_item'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
              #+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


#
# urlpatterns += patterns('',
#         (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
#         'document_root': settings.MEDIA_ROOT}))

productuser/urls.py
from django.conf.urls import url,include
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import AuthenticationForm
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy
from django.views.generic import TemplateView

from productuser.views import CreateAccount,ActivateAccount, ResendActivationEmail, ProfileDetail, ProfileUpdate, \
    PublicProfileDetail, DisableAccount

# ActivateAccount,CreateAccount,DisableAccount,ResendActivationEmail, ProfileDetail, ProfileUpdate, \
    # PublicProfileDetail

password_urls=[
    url(r'^$',RedirectView.as_view(
        pattern_name='dj-auth:pw_reset_start',
        permanent=False)),
    url(r'^change/$',
        auth_views.password_change,
        {'template_name':
            'productuser/password_change_form.html',
            'post_change_redirect':reverse_lazy(
                'dj-auth:pw_change_done')},
        name='pw_change'),
    url(r'^change/done/$',
        auth_views.password_change_done,
        {'template_name':
            'productuser/password_change_done.html'},
        name='pw_change_done'),
    url(r'^reset/$',
        auth_views.password_reset,
        {'template_name':
             'productuser/password_reset_form.html',
            'email_template_name':
                'productuser/password_reset_email.txt',
            'subject_template_name':
                'productuser/password_reset_subject.txt.txt',
            'post_reset_redirect':reverse_lazy(
                'dj-auth:pw_reset_sent')},
            name='pw_reset_start'),
    url(r'^reset/sent/$',
        auth_views.password_reset_done,
        {'template_name':
            'productuser/password_reset_sent.html'},
        name='pw_reset_sent'),
     url(r'^reset/'
        r'(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}'
        r'-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        {'template_name':
            'user/password_reset_confirm.html',
         'post_reset_redirect': reverse_lazy(
            'dj-auth:pw_reset_complete')},
        name='pw_reset_confirm'),
    url(r'reset/done/$',
        auth_views.password_reset_complete,
        {'template_name':
            'productuser/password_reset_complete.html',
         'extra_context':
             {'form':AuthenticationForm}},
        name='pw_reset_complete'),
    url(r'^disable/$',
        DisableAccount.as_view(),
        name='disable'),
    url(r'^activate/'
        r'(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}'
        r'-[0-9A-Za-z]{1,20})/$',
        ActivateAccount.as_view(),
        name='activate'),
    url(r'^create/$',
        CreateAccount.as_view(),
        name='create'),
    url(r'^create/done/$',
        TemplateView.as_view(
            template_name=(
                'productuser/user_create_done.html')),
        name='create_done'),
    url(r'^activate/resend/$',
        ResendActivationEmail.as_view(),
        name='resend_activation'),
    url(r'^activate',
        RedirectView.as_view(
            pattern_name=('dj-auth:resend_activation'),
            permanent=False)),
]

urlpatterns=[
    url(r'^$',
        RedirectView.as_view(
            pattern_name='dj-auth:login',
            permanent=False)),
    url(r'^login/$',
        auth_views.login,
        {'template_name':'productuser/login.html'},
        name='login'),
    url(r'^logout/$',
        auth_views.logout,
        {'template_name':'productuser/logged_out.html',
         'extra_context':
             {'form':AuthenticationForm}},
         name='logout'),
    url(r'^password/',include(password_urls)),
    url(r'^profile/$',
        ProfileDetail.as_view(),
        name='profile'),
    url(r'^profile/edit/$',
        ProfileUpdate.as_view(),
        name='profile_update'),
    url(r'^(?P<slug>[\w\-]+)/$',
        PublicProfileDetail.as_view(),
        name='public_profile'),
]

productuser/forms.py
from django.contrib.auth.forms import \
    UserCreationForm as BaseUserCreationForm
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.utils.text import slugify
from django.contrib.auth.forms import (
    UserChangeForm as BaseUserChangeForm,
    UserCreationForm as BaseUserCreationForm)
from productuser.models import Profile
from .utils import ActivationMailFormMixin
import logging
from django import forms

logger=logging.getLogger(__name__)


class ResendActivationEmailForm(ActivationMailFormMixin,
                                forms.Form):
    email=forms.EmailField()
    mail_validation_error = (
        'Could not re-send activation email'
        'Please try again later(Sorry)')

    def save(self,**kwargs):
        User=get_user_model()
        try:
            user=User.objects.get(email=self.cleaned_data['emai'])
        except:
            logger.warning(
                'Resend activation: No user with email: {}'
                .format(self.cleaned_data['email']))
            return None
        self.send_mail(user=user,**kwargs)
        return user

class UserCreationForm(ActivationMailFormMixin,BaseUserCreationForm):
    name=forms.CharField(max_length=255,help_text=(
        "The name displayed on your public profile"))

    mail_validation_error = (
        'User created. Could not send'
        'activation email. Please try '
        'again later. (Sorry)')

    class Meta(BaseUserCreationForm.Meta):
        model=get_user_model()
        fields=('name','email',)


    def clean_name(self):
        name=self.cleaned_data['name']
        disallowed=(
            'activate',
            'create',
            'disable',
            'login',
            'logout',
            'password',
            'profile',
        )

        if name in disallowed:
            raise ValidationError(
                "A user with that name already exists")
        return name

    def save(self,**kwargs):
        user=super().save(commit=False)
        if not user.pk:
            user.is_active=False
            send_mail=True
        else:
            send_mail=False
        user.save()
        self.save_m2m

        Profile.objects.update_or_create(
            user=user,
            defaults={
                'name':self.cleaned_data['name'],
                'slug':slugify(self.cleaned_data['name']),
            })
        if send_mail:
            self.send_mail(user=user,**kwargs)
        return user


class UserChangeForm(BaseUserChangeForm):
    class Meta(BaseUserChangeForm.Meta):
        model=get_user_model()

productuser/views.py
from django.shortcuts import render
from django.conf import settings
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.views.generic import DetailView,UpdateView
from django.views.generic import View
from django.contrib.auth import get_user, logout, get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.template.response import TemplateResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_protect
from django.core.urlresolvers import reverse_lazy
from productuser.models import Profile
from .forms import UserCreationForm, ResendActivationEmailForm
from .utils import MailContextViewMixin, ProfileGetObjectMixin
from django.views.decorators.debug import sensitive_post_parameters
from django.contrib.messages import error,success
from django.views.decorators.cache import never_cache
from django.contrib.auth.tokens import \
    default_token_generator as token_generator
from .forms import UserCreationForm
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import AuthenticationForm

class ResendActivationEmail(MailContextViewMixin,View):
    form_class=ResendActivationEmailForm
    success_url=reverse_lazy('dj-auth:login')
    template_name='productuser/resend_activation.html'

    @method_decorator(csrf_protect)
    def get(self,request):
        return TemplateResponse(
            request,
            self.template_name,
            {'form':self.form_class()})

    @method_decorator(csrf_protect)
    def post(self,request):
        bound_form=self.form_class(request.POST)
        if bound_form.is_valid():
            user=bound_form.save(**self.get_save_kwargs(request))
            if(user is not None
               and not bound_form.mail_sent):
                errs=(bound_form.non_field_errors())
                for err in errs:
                    error(request,err)
                if errs:
                    bound_form.errors.pop('__all__')

                return TemplateResponse(
                    request,
                    self.template_name,
                    {'form':bound_form})
        success(request,
                'Activation Email Sent')
        return redirect(self.success_url)


class ActivateAccount(View):
    success_url=reverse_lazy('dj-auth:login')
    template_name='productuser/user_activate.html'

    @method_decorator(never_cache)
    def get(self,request,uidb64,token):
        User=get_user_model()
        try:
            uid=force_text(urlsafe_base64_decode(uidb64))
            user=User.objects.get(pk=uid)
        except (TypeError,ValueError,OverflowError,User.DoesNotExist):
            user=None

        if(user is not None
            and token_generator.check_token(user,token)):
            user.is_active=True
            user.save()
            success(
                request,
                'User Activated.You may now login')

            return redirect(self.success_url)
        else:
            return TemplateResponse(request,self.template_name)



class DisableAccount(View):
    success_url=settings.LOGIN_REDIRECT_URL
    template_name=(
        'productuser/user_confirm_delete.html')

    @method_decorator(csrf_protect)
    @method_decorator(login_required)
    def get(self,request):
        return TemplateResponse(
            request,self.template_name)

    @method_decorator(csrf_protect)
    @method_decorator(login_required)
    def post(self,request):
        user=get_user(request)
        user.set_unusable_password()
        user.is_active=False
        user.save()
        logout(request)
        return redirect(self.success_url)


class CreateAccount(MailContextViewMixin,View):
    form_class=UserCreationForm
    success_url=reverse_lazy('dj-auth:create_done')
    template_name='productuser/user_create.html'

    @method_decorator(csrf_protect)
    def get(self,request):
        return TemplateResponse(
            request,
            self.template_name,
            {'form':self.form_class()})

    @method_decorator(csrf_protect)
    @method_decorator(sensitive_post_parameters('password1','password2'))
    def post(self,request):
        bound_form=self.form_class(request.POST)
        if bound_form.is_valid():
            bound_form.save(**self.get_save_kwargs(request))
            if bound_form.mail_sent:
                return redirect(self.success_url)
            else:
                errs=(bound_form.non_field_errors())
                for err in errs:
                    error(request,error)
            return redirect('dj-auth:resend_activation')
        return TemplateResponse(
            request,
            self.template_name,
            {'form':bound_form})


class ProfileDetail(ProfileGetObjectMixin,DetailView):
    model=Profile

class ProfileUpdate(ProfileGetObjectMixin,UpdateView):
    template_name_suffix = '_form_update'
    fields=('about',)
    model=Profile

class PublicProfileDetail(DetailView):
    model=Profile
#
# class LogoutView(View):
#     template_name='productuser/logged_out.html'
#
#     def get(self,request):
#         response=logout(request)
#         return render(response,self.template_name)

productuser/templates/productuser/logged_out.html
{% extends parent_template|default:"productuser/base_user.html" %}

{% block title %}
{{ block.super }} - Logged Out
{% endblock %}

{% block content %}
  <div class="row">
    <div class="offset-by-two eight columns">
      <p>You've successfully logged out.</p>
      {% include "productuser/login_form.html" with login_button='Log Back In' %}
    </div>
  </div>
{% endblock %}

productuser/templates/productuser/login.html
{% extends parent_template|default:"productuser/base_user.html" %}

{% block title %}
{{ block.super }} - Login
{% endblock %}

{% block content %}
<div class="jumbotron">
    {% include "productuser/login_form.html" %}

    <div>
        <ul>
            <li><a href="{% url 'dj-auth:create' %}">
                Register New Account
            </a></li>
            <li><a href="{% url 'dj-auth:pw_reset_start' %}">
                Forgotten password?
            </a></li>
            <li><a href="{% url 'dj-auth:resend_activation' %}">
                Lost Activation Email?</a></li>
        </ul>
    </div>
</div>
{% endblock %}

productuser/templates/productuser/login_form.html
<form action="{% url 'dj-auth:login' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    {% if next %}
        <input type="hidden" name="next" value="{{ next }}"/>
    {% endif %}
    <button type="submit">
        {{ login_button|default:'Log in' }}
    </button>
</form>

productuser/templates/productuser/password_change_done.html
{% extends parent_template|default:"productuser/base_user.html" %}

{% block title %}
{{ block.super }} - Change Password
{% endblock %}

{% block content %}
  <div class="row">
    <div class="offset-by-two eight columns">
      <p>Password successfully changed.</p>
    </div>
  </div>
{% endblock %}

productuser/templates/productuser/password_change_form.html
{% extends parent_template|default:"productuser/base_user.html" %}

{% load display_form %}

{% block title %}
{{ block.super }} - Change Password
{% endblock %}

{% block content %}
{#<div class="jumbotron">#}
{#    <form action="{% url 'dj-auth:pw_change' %}" method="post">#}
{#        {% csrf_token %}#}
{#        {{ form.as_p }}#}
{#        <button type="submit" class="btn btn-primary">#}
{#            Change Password#}
{#        </button>#}
{#    </form>#}
{#</div>#}
{% url 'dj-auth:pw_change' as form_url %}
{% form form_url 'Change Password' %}
{% endblock %}

productuser/templates/productuser/password_reset_confirm.html
{% extends parent_template|default:"productuser/base_user.html" %}

{% block title %}
{{ block.super }} - Reset Password
{% endblock %}

{% block content %}
  <div class="jumbotron">
      {% if validlink %}
        <p>Enter a new password below.</p>
        <form action="{{ request.path }}" method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button class="btn btn-primary" type="submit">
            Save New Password</button>
        </form>
      {% else %}
        <p>This reset link is no longer valid.</p>
        <p>Please request a new reset email
          <a href="{% url 'dj-auth:pw_reset_start' %}">
            here</a>.</p>
      {% endif %}
  </div>
{% endblock %}

productuser/templates/productuser/password_reset_form.html
{% extends parent_template|default:"productuser/base_user.html" %}

{% block title %}
{{ block.super }} - Reset Password
{% endblock %}

{% block content %}
  <div class="jumbotron">
       <p>Reset your password by email.</p>
      <form action="{% url 'dj-auth:pw_reset_start' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">
          Send Me Reset Instructions</button>
      </form>
  </div>
{% endblock %}

productuser/templates/productuser/profile_detail.html
{% extends parent_template|default:"productuser/base_user.html" %}

{% load obfuscate_email %}

{% block title %}
{{ block.super }} -
{{ profile.user.get_full_name }}'s Profile
{% endblock %}

{% block content %}
  <div class="jumbotron">
  <div class="row">

    {% if user.pk == profile.user.pk %}
      <div class="col-sm-4">
    {% else %}
      <div class="col-sm-8">
    {% endif %}

{#    <h2>About {{ profile.user.get_full_name|obfuscate }}</h2>#}
    <h2>About {{ profile.name }}</h2>
      {{ profile.about|default:"No Profile"|linebreaks }}

       {% if user.pk == profile.user.pk %}
        <div class="col-sm-3">
        <ul>
          <li><a href="{% url 'order_history' %}">
              Order History</a></li>
          <li><a href="{{ profile.get_update_url }}">
            Edit Your Profile</a></li>
          <li><a href="{% url 'dj-auth:pw_change' %}">
            Change Password</a></li>
          <li><a href="{% url 'dj-auth:disable' %}">
            Disable Account</a></li>
        </ul>
        </div>
        {% endif %}
  </div>
  </div><!-- jumbotron -->
{% endblock %}

productuser/templates/productuser/profile_form_update.html
{% extends parent_template|default:"productuser/base_user.html" %}

{% block title %}
{{ block.super }} - Update Profile
{% endblock %}


{% block content %}
  <div class="jumbotron">
      <form action="{{ profile.get_update_url }}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">
          Update Profile</button>
      </form>
  </div>
{% endblock %}

productuser/templates/productuser/resend_activation.html
{% extends parent_template|default:"productuser/base_user.html" %}

{% block title %}
{{ block.super }} - Resend Activation E-Mail
{% endblock %}

{% block content %}
  <div class="jumbotron">
      <p>Resend your account activation email.</p>
      <form action="{% url 'dj-auth:resend_activation' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">
          Resend Activation E-Mail</button>
      </form>
  </div>
{% endblock %}

productuser/templates/productuser/user_activate.html
{% extends parent_template|default:"productuser/base_user.html" %}

{% block title %}
{{ block.super }} - Account Activation Failed
{% endblock %}

{% block content %}
<div class="jumbotron">
    <p>This activation link is no longer valid</p>
</div>
{% endblock %}

productuser/templates/productuser/user_confirm_delete.html
{% extends parent_template|default:"productuser/base_user.html" %}

{% block title %}
{{ block.super }} - Disable Account
{% endblock %}

{% block content %}
  <div class="row">
      <p>Disable your account?</p>
      <p>This cannot be undone.</p>
      <form action="{% url 'dj-auth:disable' %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">
          Disable Account</button>
      </form>
    </div>
{% endblock %}

productuser/templates/productuser/user_create.html
{% extends parent_template|default:"productuser/base_user.html" %}
{% block title %}
{{ block.super }} - Create Account
{% endblock %}

{% block content %}
<div class="jumbotron">
    <a href="{% url 'dj-auth:resend_activation' %}">
        Lost Activation Email?</a>
    <form action="{% url 'dj-auth:create' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">
            Create New Account
        </button>
    </form>
</div>
{% endblock %}

productuser/templates/productuser/user_create_done.html
{%  extends parent_template|default:"productuser/base_user.html" %}

{% block title %}
{{ block.super }}- Account Created
{% endblock %}

{% block content %}
<div class="jumbotron">
    <p>Your account has been created</p>
    <p>Please check your email for the activation link</p>
</div>
{% endblock %}