DjangoViews/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.views.generic import RedirectView

from DjangoViews.views import SlugView
from contact.views import ContactView
from order.views import OrderView, ShipmentDetail, OrderHistoryView, OrderDetailView
from products.views import BrandCreate, BrandDetail, BrandList, BrandUpdate, BrandDelete, ProductCreate, ProductDetail, \
    ProductUpdate, ProductDelete, ProductList, CategoryDetail
from location.views import CountryDetail, CountryList, CountryUpdate, CountryDelete, CountryCreate
from django.conf.urls import url,include
from productuser import urls as user_urls
from django.conf import settings
from django.conf.urls.static import static
from cart.views import AddToCartView,CartDetail,CartEmptyView, RemoveCartItemView
from core.views import page_not_found
from products.ajax import add_comment,get_comments
from django.conf.urls import (
    handler400, handler403, handler404, handler500
)

from stores.views import StoreDetail, StoreList
from cart.ajax import get_cart_item_count, remove_cart_item

handler404 = page_not_found

urlpatterns = [
    url(r'^$',RedirectView.as_view(
        pattern_name='product_list',
        permanent=False)),
    url(r'^stores/$',StoreList.as_view(),name='store_list'),
    url(r'^admin/', admin.site.urls),
    url(r'^user/',include(user_urls,
                          app_name='productuser',
                          namespace='dj-auth')),
    url(r'^category/(?P<slug>[\w\-]+)/$',CategoryDetail.as_view(),name='category_detail'),
    # url(r'^brands/$',BrandList.as_view(),name='brand_list'),
    #url(r'^brand/create/$',BrandCreate.as_view(),name='brand_create'),
    url(r'^brand/(?P<slug>[\w\-]+)/$',BrandDetail.as_view(),name='brand_detail'),
    #url(r'^brand/(?P<slug>[\w\-]+)/update/$',BrandUpdate.as_view(),name='brand_update'),
    #url(r'^brand/(?P<slug>[\w\-]+)/delete/$',BrandDelete.as_view(),name='brand_delete'),
    url(r'^products/$',ProductList.as_view(),name='product_list'),
    # url(r'^product/create/$',ProductCreate.as_view(),name='product_create'),
    url(r'^product/(?P<product_id>[^/]+)/$',ProductDetail.as_view(),name='product_detail'),
    # url(r'^product/(?P<product_id>[^/]+)/update/$',ProductUpdate.as_view(),name='product_update'),
    # url(r'^product/(?P<product_id>[^/]+)/delete/$', ProductDelete.as_view(), name='product_delete'),
    url(r'^countries/$',CountryList.as_view(),name='country_list'),
    # url(r'^country/create/$',CountryCreate.as_view(),name='country_create'),
    # url(r'^country/(?P<slug>[\w\-]+)/$',CountryDetail.as_view(),name='country_detail'),
    # url(r'^country/(?P<slug>[\w\-]+)/update/$',CountryUpdate.as_view(),name='country_update'),
    # url(r'^country/(?P<slug>[\w\-]+)/delete/$',CountryDelete.as_view(),name='country_delete'),
    url(r'^contact/$',ContactView.as_view(),name='contact_create'),
    url(r'^addtocart/(?P<product_id>[^/]+)/$',AddToCartView.as_view(),name='add_to_cart'),
    url(r'^cart/$',CartDetail.as_view(),name='cart_detail'),
    url(r'^cart/empty/$',CartEmptyView.as_view(),name='cart_empty'),
    url(r'^order/$',OrderView.as_view(),name='order_form'),
    url(r'^shipment/(?P<shipment_id>[^/]+)/$',ShipmentDetail.as_view(),name='shipment_detail'),
    url(r'^order/history/$',OrderHistoryView.as_view(),name='order_history'),
    url(r'^order/(?P<order_id>[^/]+)/$',OrderDetailView.as_view(),name='order_detail'),
    url(r'^(?P<slug>[\w\-]+)/$',SlugView.as_view(),name='slug_view'),
    url(r'^ajax/add_comment/$',add_comment),
    url(r'^ajax/get_comments/$',get_comments),
    url(r'^ajax/get_cart_item_count/$',get_cart_item_count),
    url(r'^ajax/remove_cart_item/$',remove_cart_item),
    url(r'^store/(?P<slug>[\w\-]+)/$',StoreDetail.as_view(),name='store_detail'),
    url(r'^cart/remove_cart_item/$',RemoveCartItemView.as_view(),name='remove_cart_item'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
              #+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


#
# urlpatterns += patterns('',
#         (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
#         'document_root': settings.MEDIA_ROOT}))

productuser/urls.py
from django.conf.urls import url,include
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import AuthenticationForm
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy
from django.views.generic import TemplateView

from productuser.views import CreateAccount,ActivateAccount, ResendActivationEmail, ProfileDetail, ProfileUpdate, \
    PublicProfileDetail, DisableAccount

# ActivateAccount,CreateAccount,DisableAccount,ResendActivationEmail, ProfileDetail, ProfileUpdate, \
    # PublicProfileDetail

password_urls=[
    url(r'^$',RedirectView.as_view(
        pattern_name='dj-auth:pw_reset_start',
        permanent=False)),
    url(r'^change/$',
        auth_views.password_change,
        {'template_name':
            'productuser/password_change_form.html',
            'post_change_redirect':reverse_lazy(
                'dj-auth:pw_change_done')},
        name='pw_change'),
    url(r'^change/done/$',
        auth_views.password_change_done,
        {'template_name':
            'productuser/password_change_done.html'},
        name='pw_change_done'),
    url(r'^reset/$',
        auth_views.password_reset,
        {'template_name':
             'productuser/password_reset_form.html',
            'email_template_name':
                'productuser/password_reset_email.txt',
            'subject_template_name':
                'productuser/password_reset_subject.txt.txt',
            'post_reset_redirect':reverse_lazy(
                'dj-auth:pw_reset_sent')},
            name='pw_reset_start'),
    url(r'^reset/sent/$',
        auth_views.password_reset_done,
        {'template_name':
            'productuser/password_reset_sent.html'},
        name='pw_reset_sent'),
     url(r'^reset/'
        r'(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}'
        r'-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        {'template_name':
            'user/password_reset_confirm.html',
         'post_reset_redirect': reverse_lazy(
            'dj-auth:pw_reset_complete')},
        name='pw_reset_confirm'),
    url(r'reset/done/$',
        auth_views.password_reset_complete,
        {'template_name':
            'productuser/password_reset_complete.html',
         'extra_context':
             {'form':AuthenticationForm}},
        name='pw_reset_complete'),
    url(r'^disable/$',
        DisableAccount.as_view(),
        name='disable'),
    url(r'^activate/'
        r'(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}'
        r'-[0-9A-Za-z]{1,20})/$',
        ActivateAccount.as_view(),
        name='activate'),
    url(r'^create/$',
        CreateAccount.as_view(),
        name='create'),
    url(r'^create/done/$',
        TemplateView.as_view(
            template_name=(
                'productuser/user_create_done.html')),
        name='create_done'),
    url(r'^activate/resend/$',
        ResendActivationEmail.as_view(),
        name='resend_activation'),
    url(r'^activate',
        RedirectView.as_view(
            pattern_name=('dj-auth:resend_activation'),
            permanent=False)),
]

urlpatterns=[
    url(r'^$',
        RedirectView.as_view(
            pattern_name='dj-auth:login',
            permanent=False)),
    url(r'^login/$',
        auth_views.login,
        {'template_name':'productuser/login.html'},
        name='login'),
    url(r'^logout/$',
        auth_views.logout,
        {'template_name':'productuser/logged_out.html',
         'extra_context':
             {'form':AuthenticationForm}},
         name='logout'),
    url(r'^password/',include(password_urls)),
    url(r'^profile/$',
        ProfileDetail.as_view(),
        name='profile'),
    url(r'^profile/edit/$',
        ProfileUpdate.as_view(),
        name='profile_update'),
    url(r'^(?P<slug>[\w\-]+)/$',
        PublicProfileDetail.as_view(),
        name='public_profile'),
]

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        Django Store
        {% endblock %}
    </title>
      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--[if IE]><script
      src="http://html5shiv.googlecode.com/svn/trunk/html5.js">
    </script><![endif]-->
    <link rel="stylesheet" type="text/css" href="{% static 'site/bootstrap.css' %}">
    <script type="text/javascript" src="{% static  'site/bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static  'site/jquery-3.1.1.js' %}"></script>
	<script src="{% static "site/js/reconnecting-websocket.min.js" %}" type="text/javascript"></script>
    <script type="text/javascript" src="{% static  'site/js/get_cart_item_count.js' %}"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            get_cart_item_count();

            $.get()

            var ws_scheme=window.location.protocol=="https:"?"wss":"ws";
            var email=btoa($("#hdn_email").val());
            var ws_path=ws_scheme+"://"+window.location.host+"/stream/"+email+"/";
            console.log("Connecting to "+ws_path);
            var socket=new ReconnectingWebSocket(ws_path);

            socket.onmessage=function(message){
                console.log("Got message "+message.data);
                var data=JSON.parse(message.data);
                $("#cart_item_count").html(data);
                //$("#data").html('<p>'+data+'</p>');
            };

            socket.onopen=function(){}
            socket.onclose=function () {

            }
        });

    </script>


    {% block head %}{% endblock %}
</head>
<body>
    <input type="hidden" id="hdn_email" value="{{ user.email }}"/>
  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Django Store</a>
    </div>
    <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'product_list' %}">Products</a></li>
        <li><a href="{% url 'store_list' %}">Stores</a></li>
        <li><a href="{% url 'contact_create' %}">Contact</a></li>
        {% if user.is_authenticated %}
            <li><a href="{% url 'dj-auth:profile' %}">View Profile</a></li>
            <li><a href="{% url 'cart_detail' %}">View Cart<span id="cart_item_count" class="badge"></span></a></li>
            <li><a href="{% url 'order_history' %}">Order History</a></li>
            <li><a href="#">{{ user.email }}</a></li>
            <li><a href="{% url 'dj-auth:logout' %}?next={{ request.path }}">Log Out</a></li>
        {% else %}
            <li><a href="{% url 'dj-auth:login' %}?next={{ request.path }}">Log In</a></li>
            <li><a href="{% url 'dj-auth:create' %}">Register</a></li>
        {% endif %}
    </ul>
  </div>
</nav>
{#  <header>#}
{#      <h1>Order Manager</h1>#}
{#  </header>#}
    {% if messages %}
    <div>
        <ul>
            {% for message in messages %}
               <div class="alert alert-danger" role="alert">
                  <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                  <span class="sr-only">Error:</span>
                  {{ message }}
                </div>
            {% endfor %}
        </ul>
    </div>
    {% endif %}

    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>